### ISSUE TITLE
Question 14 and Question 63

### ISSUE THREAD

**Issue by SamuelPavlik** [Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers#10]
I think both of these should rather be answered with "rolling with additional batches". It is the cheaper option, maintains the full capacity and, in the case of question 14, uses existing instances.

**Comment by danieldanielecki** [comment]
Question 14 - The current answer stays because the same instances are used while deploying, and the total capacity is maintained.

Question 63 - you are correct; fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers/commit/97e8f9c13b8fe4237acccc7b22d1a314e40a3993.

**Comment by Patimir** [comment]
Are you sure about the question 14? Based on the documentation [here](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.deploy-existing-version.html) the immutable deployment is "A slower deployment method, that ensures your new application version is always deployed to **new instances**, instead of updating existing instances." I believe the correct answer is "rolling with additional batches".

**Comment by danieldanielecki** [comment]
Thanks for the follow up, I wasn't sure indeed; fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Developer-Associate-DVA-C02-Practice-Tests-Exams-Questions-Answers/commit/ba490e58a7b3e0c5720fd411944cd62ff28a0f02!
